swagger: '2.0'
info:
  version: 1.0.0
  title: Component Desing Sample - Mock API
  description: Mock API project to be used for e2e tests
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:5000
basePath: /
tags:
  - name: Profiles
    description: API for users in the system
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /profiles:
    get:
      tags:
        - Profiles
      summary: Get all profiles
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Profile'
  /profiles/{id}:
    get:
      tags:
        - Profiles
      summary: Get profile based on given id parameter
      parameters:
        - name: id
          type: integer
          in: path
          description: Profile id
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Profile'
        '404':
          description: The specified profile ID is invalid (not a number)
  /bookings:
    get:
      tags:
        - Bookings
      summary: Get all bookings
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Booking'
    post:
      tags:
        - Bookings
      summary: Create a new booking
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Booking'
      responses:
        '201':
          description: Created
  /bookings/{id}:
    get:
      tags:
        - Bookings
      summary: Get profile based on given id parameter
      parameters:
        - name: id
          type: integer
          in: path
          description: Booking id
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Booking'
        '404':
          description: The specified booking ID is invalid (not a number)
definitions:
  Profile:
    type: object
    required:
      - profileImage
      - fullName
      - link
      - userName
      - basePrice
      - currency
      - isDailyPrice
      - skills
      - hourAvailability
      - isAvailable
    properties:
      profileImage:
        type: string
      fullName:
        type: string
      link:
        type: string
      userName:
        type: string
      basePrice:
        type: number
      currency:
        type: string
      isDailyPrice:
        type: boolean
      skills:
        type: array
        items:
          type: string
      hourAvailability:
        type: number
  Booking:
    type: object
    required:
      - beginDate
      - endDate
      - profileId
      - totalPrice
      - notes
    properties:
      beginDate:
        type: string
      endDate:
        type: string
      profileId:
        type: number
      totalPrice:
        type: number
      notes:
        type: string
      status:
        type: string
      tax:
        type: number
      attachment:
        type: string
